version: '3'

services:
  db:
    restart: unless-stopped
    image: postgres
    environment:
      - PGPORT=5432

  filament:
    restart: unless-stopped
    build: .
    depends_on:
      - db
    environment:
      - filament_port=80
      - NODE_ENV=production
      - PGHOST=db
      - PGPORT=5432
    ports:
      - "80:80"
    links:
      - db
