version: '3'

services:
  filament:
    restart: unless-stopped
    build: .
    environment:
      - filament_sentryKey=${filament_sentryKey}
      - filament_port=80
      - NODE_ENV=production
      - PGHOST=db
      - PGPORT=5432
    ports:
      - "80:80"
